repos:
    - repo: https://github.com/LiquidFun/aoc_tiles
      rev: 0.6.2
      hooks:
          - id: aoc-tiles
          - --auto-add-tiles-to-git=amend
            #     - --language-sorting=jl,kt,py,rs
            #     - --exclude-patterns=2021/*/*.apl,2021/*/*.py,2021/*/*.cpp